import React, { useState } from 'react';
import { ShieldCheck, CheckCircle2, Copy, ExternalLink, Building2, MapPin, Hash, Calendar, FileText, Sparkles } from 'lucide-react';

export default function UdiseVerification() {
  const [copied, setCopied] = useState(false);

  const copyUdise = () => {
    navigator.clipboard.writeText('10024102835');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section id="udise" className="py-16 bg-slate-950 border-y border-slate-800/80 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-12 space-y-3">
          <div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/30 px-3.5 py-1 rounded-full text-xs font-bold text-emerald-400">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Official Government Recognition</span>
          </div>
          
          <h2 className="text-3xl sm:text-4xl font-heading font-extrabold text-white">
            Ministry of Education (MoE) <span className="gold-gradient-text">UDISE+ Approval</span>
          </h2>
          
          <p className="text-sm sm:text-base text-slate-300">
            V.N. Public School is officially registered and recognized with an active UDISE Code generated by the Ministry of Education, Government of India.
          </p>
        </div>

        {/* Interactive UDISE Card simulating official screenshot */}
        <div className="max-w-4xl mx-auto bg-slate-900 border-2 border-amber-400/30 rounded-2xl shadow-2xl overflow-hidden backdrop-blur-md">
          
          {/* Card Header Bar */}
          <div className="bg-gradient-to-r from-blue-900 via-slate-900 to-blue-950 px-6 py-4 border-b border-slate-800 flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-amber-400/20 border border-amber-400/40 flex items-center justify-center font-bold text-amber-400 text-lg">
                UD
              </div>
              <div>
                <div className="text-xs text-amber-300 font-semibold uppercase tracking-wider">UDISE+ Code Application Portal</div>
                <div className="text-base font-bold text-white">Ministry of Education (MoE) Verified Record</div>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={copyUdise}
                className="bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 border border-amber-400/30 px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors"
              >
                {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied Code!' : 'Copy UDISE Code'}</span>
              </button>
            </div>
          </div>

          {/* Grid of Verified Data */}
          <div className="p-6 sm:p-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            
            {/* Field 1: UDISE Code */}
            <div className="bg-slate-950 p-4 rounded-xl border border-amber-400/30 relative">
              <div className="text-xs text-slate-400 font-medium mb-1 flex items-center gap-1.5">
                <Hash className="w-3.5 h-3.5 text-amber-400" /> UDISE Code
              </div>
              <div className="text-2xl font-mono font-black text-amber-400 tracking-wider">
                10024102835
              </div>
              <div className="mt-1 text-[11px] text-emerald-400 font-semibold flex items-center gap-1">
                <CheckCircle2 className="w-3 h-3" /> Active & Approved
              </div>
            </div>

            {/* Field 2: School Request Id */}
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
              <div className="text-xs text-slate-400 font-medium mb-1 flex items-center gap-1.5">
                <FileText className="w-3.5 h-3.5 text-blue-400" /> School Request ID
              </div>
              <div className="text-xl font-mono font-bold text-white">
                BR1103739
              </div>
              <div className="mt-1 text-[11px] text-slate-400">
                Bihar State Portal
              </div>
            </div>

            {/* Field 3: Registration Number */}
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
              <div className="text-xs text-slate-400 font-medium mb-1 flex items-center gap-1.5">
                <ShieldCheck className="w-3.5 h-3.5 text-amber-400" /> Govt Reg. Number
              </div>
              <div className="text-sm font-mono font-bold text-amber-200 break-all">
                20411042202441222160413
              </div>
              <div className="mt-1 text-[11px] text-slate-400">
                Official School Registration
              </div>
            </div>

            {/* Field 4: School Name */}
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
              <div className="text-xs text-slate-400 font-medium mb-1 flex items-center gap-1.5">
                <Building2 className="w-3.5 h-3.5 text-blue-400" /> Recognized School Name
              </div>
              <div className="text-base font-bold text-white">
                V.N PUBLIC SCHOOL
              </div>
              <div className="mt-1 text-[11px] text-slate-400">
                Nimuiya Turkauliya
              </div>
            </div>

            {/* Field 5: District & Block */}
            <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
              <div className="text-xs text-slate-400 font-medium mb-1 flex items-center gap-1.5">
                <MapPin className="w-3.5 h-3.5 text-red-400" /> District & Block
              </div>
              <div className="text-sm font-bold text-slate-200">
                Purba Champaran - 1002
              </div>
              <div className="text-xs text-slate-400">
                Turkaulia Block (100227)
              </div>
            </div>

            {/* Field 6: Approval Status */}
            <div className="bg-emerald-950/40 p-4 rounded-xl border border-emerald-500/40">
              <div className="text-xs text-emerald-300 font-medium mb-1 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-emerald-400" /> Approval Status
              </div>
              <div className="text-sm font-bold text-emerald-400">
                Approved By MoE
              </div>
              <div className="text-[11px] text-emerald-200 mt-1 font-mono">
                UDISE Code Generated
              </div>
            </div>

          </div>

          {/* Bottom Callout */}
          <div className="bg-slate-950/90 border-t border-slate-800 px-6 py-4 flex flex-wrap items-center justify-between text-xs text-slate-400 gap-2">
            <span className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Parents can verify this status directly on the Ministry of Education UDISE+ Portal.</span>
            </span>
            <a
              href="https://udiseplus.gov.in"
              target="_blank"
              rel="noreferrer"
              className="text-amber-400 hover:text-amber-300 font-semibold flex items-center gap-1 underline"
            >
              <span>Visit UDISE+ Portal</span>
              <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>

        </div>

      </div>
    </section>
  );
}
